title: <p align="center"> Yukta Bajaj </p>
logo: /assets/img/yukta.jpg

description:
  <a href="https://www.linkedin.com/in/bajajyukta7/">LinkedIn</a>|
  Email- href{mailto:bajajyukta7@gmail.com}{bajajyukta7@gmail.com}|
  Mobile- +918804522302
  
  <br>   
  Passionate Software Engineer currently working in cloud computing at Microsoft Azure.
  Strong engineering professional with a B.Tech. in Comffputer Science and Engineering from IIT Dhanbad. 
  Always motivated at finding solution to impromptu requirements in the team.
  <br>
  Education-
    institution- IIT(ISM) Dhanbad
    degree- BTech. in Computer Science
    date- May 2019
    location- Dhanbad, India
    gpa- 9.23/10.0
  <br>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
