title: <p align="center"> Yukta Bajaj </p>
logo: /assets/img/yukta.jpg

description: |
  bajajyukta7@gmail.com|
  +918804522302
  <br>
  Passionate Software Engineer currently working in cloud computing at Microsoft Azure.
  Strong engineering professional with a B.Tech. in Computer Science and Engineering from IIT Dhanbad.
  Always motivated at finding solutions to impromptu requirements in the team.
  <br>
  Education:
  - IIT(ISM) Dhanbad<br>
  - BTech. in Computer Science<br>
  - May 2019 | Dhanbad, India<br>
  - GPA 9.23/10.0
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
